version: '3.8'

services:
  ml-sentinel:
    build:
      context: ..
      dockerfile: ec2/Dockerfile
    container_name: ml-sentinel-app
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    restart: always
